arena:
  height_m: 0.80
  width_m: 0.80
display:
  display_index: 0
  fullscreen: false
grid:
  resolution_m: 0.02 # 2 cm par cellule
robot:
  # Rayon physique du robot (Turtlebot Burger ~9cm)
  radius_m: 0.09
  # Marge de sécurité supplémentaire pour ne pas frotter les murs
  inflation_margin_m: 0.05
obstacles: []
projector:
  height: 960
  margin: 50
  margin_px: 50
  width: 1280
transform:
  H_C2W:
    - - -0.0010267945196526461
      - -3.730098981565071e-05
      - 1.5189658207743262
    - - -3.418757045764291e-05
      - 0.0015329706593207066
      - -0.5017419121719356
    - - -9.992942953194014e-07
      - 2.247742515662756e-05
      - 1.0
  scale: 0.5720342439860417
  scale_m_per_av: 0.5720342439860417
