game:
  mode: "DEATHMATCH"
  duration: 180         # Durée de la partie en secondes (3 min)
  
  shooting:
    cooldown: 1.0       # Temps d'attente entre deux tirs (secondes)
    max_range: 10.0     # Portée maximale du tir (mètres)
    hit_radius: 0.15    # Rayon de la hitbox autour du robot (mètres) - UTILISÉ PAR L'ARBITRE

  mock:
    # Positions de départ pour le mode simulation
    ai_start_pos: [0.2, 0.5, 0.0]   # x%, y%, theta (relative to arena instructions in Manager)
    human_start_pos: [0.8, 0.5, 3.14] 
