projector:
  width: 1024
  height: 768
  
display:
  monitor_offset_x: 1920
  borderless: true
  fullscreen: false

visuals:
  projectile_speed_px_s: 800.0  # Vitesse du projectile en pixels/seconde
  
  colors:
    background: [10, 10, 20]
    grid: [30, 30, 50]
    ai: [0, 150, 255]
    human: [255, 50, 0]
    hitbox: [255, 255, 0]
    
  hitbox:
    radius_m: 0.15 # Doit correspondre Ã  game.yaml/shooting/hit_radius
